# Generated by Django 2.0.6 on 2019-04-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesdetails',
            name='vehicle_isavailable',
            field=models.BooleanField(default=False),
        ),
    ]
