# Generated by Django 2.0.6 on 2019-04-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0003_auto_20190406_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesdetails',
            name='vehicle_model',
            field=models.BigIntegerField(default=0),
        ),
    ]
