# Generated by Django 2.0.6 on 2019-04-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0004_vehiclesdetails_vehicle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecompany',
            name='company_name',
            field=models.CharField(default='', max_length=225, unique=True),
        ),
    ]
