# Generated by Django 2.0.6 on 2019-04-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0005_auto_20190416_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecategories',
            name='vehicle_category_name',
            field=models.CharField(default='', max_length=225, unique=True),
        ),
    ]
