# Generated by Django 2.0.6 on 2019-04-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0006_auto_20190416_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesdetails',
            name='vehicle_image',
            field=models.CharField(default='', max_length=225, null=True),
        ),
    ]
