# Generated by Django 2.0.6 on 2019-04-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0008_auto_20190425_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesdetails',
            name='seats',
            field=models.CharField(default='', max_length=255),
        ),
    ]
