# Generated by Django 2.0.6 on 2019-04-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0009_auto_20190425_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesdetails',
            name='airbags',
            field=models.CharField(default='', max_length=255),
        ),
    ]
