# Generated by Django 2.0.6 on 2019-05-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerapp', '0010_auto_20190425_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesdetails',
            name='role_id',
            field=models.IntegerField(null=True),
        ),
    ]
