# Generated by Django 2.0.6 on 2019-04-05 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=255)),
                ('user_email', models.CharField(default='', max_length=180)),
                ('user_mobile', models.CharField(default='', max_length=180)),
                ('user_subject', models.CharField(default='', max_length=180)),
                ('user_message', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MySiteUser',
            fields=[
                ('user_name', models.CharField(default='', max_length=255)),
                ('user_email', models.EmailField(default='', max_length=225, primary_key=True, serialize=False)),
                ('user_password', models.CharField(default='', max_length=20)),
                ('user_mobile', models.CharField(default='', max_length=255)),
                ('user_gender', models.CharField(default='', max_length=10)),
                ('user_isactive', models.BooleanField(default=True)),
                ('user_dob', models.CharField(default='', max_length=255)),
                ('user_image', models.CharField(max_length=255, null=True)),
                ('user_isavailable', models.BooleanField(default=True)),
                ('user_isqueue', models.BooleanField(default=False)),
                ('last_login', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(default='', max_length=225, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='mysiteuser',
            name='site_role_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='front_app.User_role'),
        ),
    ]
