# Generated by Django 2.0.6 on 2019-04-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_details',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(default='', max_length=225)),
                ('logi_time', models.CharField(default='', max_length=225)),
                ('logout_time', models.CharField(default='', max_length=225)),
            ],
        ),
        migrations.RenameField(
            model_name='mysiteuser',
            old_name='user_name',
            new_name='user_fname',
        ),
        migrations.AddField(
            model_name='mysiteuser',
            name='user_lname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mysiteuser',
            name='user_gender',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='mysiteuser',
            name='user_mobile',
            field=models.BigIntegerField(default=0),
        ),
    ]
