# Generated by Django 2.0.6 on 2019-04-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysiteuser',
            name='last_login',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
