# Generated by Django 2.0.6 on 2019-04-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0002_auto_20190411_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysiteuser',
            old_name='last_login',
            new_name='registered_on',
        ),
    ]
