# Generated by Django 2.0.6 on 2019-04-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0003_auto_20190411_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_details',
            old_name='logi_time',
            new_name='login_time',
        ),
    ]
