# Generated by Django 2.0.6 on 2019-04-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0004_auto_20190411_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysiteuser',
            name='otp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mysiteuser',
            name='otp_time_generation',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
