# Generated by Django 2.0.6 on 2019-04-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0006_auto_20190413_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysiteuser',
            name='isverified',
            field=models.BooleanField(default=False),
        ),
    ]
