# Generated by Django 2.0.6 on 2019-04-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0007_mysiteuser_isverified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysiteuser',
            old_name='isverified',
            new_name='user_isverified',
        ),
    ]
