# Generated by Django 2.0.6 on 2019-05-01 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0011_booking_details_vehicle_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='amount_exp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking_details',
            name='invoice',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='booking_details',
            name='seller_detail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking_details',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='user_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='front_app.MySiteUser'),
        ),
    ]
