# Generated by Django 2.0.6 on 2019-05-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0012_auto_20190501_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='booking_date',
            field=models.CharField(default='', max_length=255),
        ),
    ]
