# Generated by Django 2.0.6 on 2019-05-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0014_booking_details_cancel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
