# Generated by Django 2.0.6 on 2019-05-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0015_booking_details_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='cancellation_time',
            field=models.CharField(default='', max_length=255),
        ),
    ]
