# Generated by Django 2.0.6 on 2019-05-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0016_booking_details_cancellation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
