# Generated by Django 2.0.6 on 2019-05-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0017_auto_20190503_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='return_date',
            field=models.CharField(default='', max_length=255),
        ),
    ]
