# Generated by Django 2.0.6 on 2019-05-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0019_remove_booking_details_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
