# Generated by Django 2.0.6 on 2019-05-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0020_booking_details_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
