# Generated by Django 2.0.6 on 2019-05-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0021_auto_20190504_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
