# Generated by Django 2.0.6 on 2019-05-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0022_auto_20190504_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_details',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='end_date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='start_date',
            field=models.CharField(default='', max_length=255),
        ),
    ]
