# Generated by Django 2.0.6 on 2019-05-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app', '0027_payment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
